### ISSUE TITLE
Event Total Cost

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/nutshell-renaissance-fair#91] opened 2019-11-23 19:53 UTC
## User Story
**As a user**, I should be able to see the total cost of a specific event.

## AC
*WHEN* I am on a specific event page I should see a table, split by module,
*AND* with the cost set center.
*THEN* Subtotals under each module,
*AND* a total cost under all of the Module tables.

## DEV
* Requires each component to have  their own respective smash function `getComponentByEventId();` in order to build the full Smash function for all components (see example below)
*  `reduce()` by each module and `reduce()` add subtotals of each reduced module.

**Comment by evangdesigns** [comment] 2019-11-26 00:56
*Partial Smash*
```
const totalCosts = () => new Promise((resolve, reject) => {
  eventData.getEvents(eventId)
    .then((eventId) => {
    foodData.getFoodsByEventId(eventId)
      .then((eventId) => {
      showsData.getShowsByEventId(eventId)
        .then((EventId) => {
          souveniersData.getSuoviesByEventId(eventId)
          const events = [];
          costs.forEach((cost) => {
          // loop through all event info building the table.
        });
        resolve(eventCosts);
      });
    });
  })
    .catch((error) => reject(error));
});
```

**Comment by evangdesigns** [comment] 2019-11-26 01:03
<img width="379" alt="Screen Shot 2019-11-24 at 7 04 19 PM" src="https://user-images.githubusercontent.com/26425684/69590790-3ec84c00-0fb6-11ea-85ea-15467c697501.png">

**Comment by zoeames** [comment] 2019-11-26 01:52
this is a duplicate of #90

**Closed as completed by zoeames** 2019-11-26 01:52 UTC
